pipeline{
    agent {
      node {
	label 'slave-1'
    }
}

    tools {
         maven 'MAVEN_HOME'
         jdk 'JAVA_HOME'
         git 'GIT_HOME'
    }

    stages{
        stage('pre-build step') {
            steps {
		sh '''
                echo "Pre Build Step for Webhook Trigges the pipeline on push event"
		'''
	    }
	}
        stage('Git Checkout'){
            steps{  
	     checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/rajeshrajaroyal/Project-Management.git']])
	    }    
        }
        stage('build'){
            steps{
               sh '''
                mvn package
                '''
            }
        }
        stage ('Unit Test') {
	        steps {
                echo 'Running Unit Testing'
                sh '''
                mvn test
                '''
             }
         }
        stage ('Update Local Repository') {
             steps {
                  sh '''
                     mvn install
                  '''
             }
        }
        stage ('Static Code Analysis') {
             environment {
             scannerHome = tool 'SONAR_SCANNER'
             }
             steps {
                echo 'Running Static Code Analysis'
                 withSonarQubeEnv('SONAR_HOME') {
                 sh '${scannerHome}/bin/sonar-scanner'
                 }
            }
        }
	stage('Jfrog Artifact Upload') {
            steps {
              rtUpload (
                serverId: 'artifactory',
                spec: '''{
                      "files": [
                        {
                          "pattern": "*.war",
                           "target": "local-snapshot-repo"
                        }
                    ]
                }'''
              )
          }
        }
        stage ('Tomcat Deployment') {
           steps {
             script { 
             deploy adapters: [tomcat7(credentialsId: 'tomcat-credentials', path: '', url: 'http://13.200.242.131:8080/')], contextPath: '/webapp-app', war: '**/*.war'      
	     }
		   
                  }
           }
         stage('post-build step') {
            steps {
		sh '''
                echo "Successfull Pipeline for Tomcat Deployment"
		'''
	    }
	}
    
     }
}
