pipeline {
    agent {
        node {
            label 'slave-1'
        }
    }
    stages {
        stage('Git Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/rajeshrajaroyal/Project-Management.git']]])
                sh 'pwd'
            }
        }

        stage('Terraform init') {
            steps {
                dir('Project/Task'){
                  sh 'terraform init'
                  sh 'pwd'
                }
            }

        }
        stage('Terraform validate') {
            steps {
                dir('Project/Task'){
                  sh 'terraform validate'
                  sh 'pwd'
                }
            }
        }
        stage('Terraform plan') {
            steps {
                dir('Project/Task'){
                  sh 'terraform plan'
                  sh 'pwd'
                }
            }
        }
        stage('Terraform apply/destroy') {
            parallel {
                stage('Terraform apply') {
                    when {
                        expression {
                            "$State" == "apply"
                        }
                    }
                    steps {
                        dir('Project/Task'){
                          sh 'terraform apply --auto-approve'
                          sh 'pwd'
                        }
                    }
                }
                stage('Terraform destroy') {
                    when {
                        expression {
                            "$State" == "destroy"
                        }
                    }
                    steps {
                        dir('Project/Task'){
                          sh 'terraform destroy --auto-approve'
                          sh 'pwd'
                        }
                    }
                }
            }
        }
    }
}
